### PR TITLE
Release v2.1.1

### PR DESCRIPTION
**Pull request by legobeat**
This is the first release of this fork under the new name `@lavamoat/sourcemap-validator`.

#### Changes from v2.1.0
- Rename to `@lavamoat/sourcemap-validator`
- [Replace unmaintained lodash per-method packages with full lodash](https://github.com/LavaMoat/sourcemap-validator/commit/7b801f0db6caf5e9438d46faa57fe5a118962a55)

[diff](https://github.com/LavaMoat/sourcemap-validator/compare/master...LavaMoat:sourcemap-validator:release/2.1.1)

### CODE REVIEW

**Comment by boneskull** [comment]
What prompted this fork?

**Review by boneskull — COMMENTED** [review]
What prompted this fork?  Vulns in those lodash packages?

**Comment by boneskull** [comment]
IMO as long as we're here, we should rip out lodash:

- `forEach` is not needed
- `template` can be replaced with template literals

**Comment by legobeat** [comment]
> Vulns in those lodash packages?

For `lodash-template` yes (see linked PR), that's part of it. We also at minimum want #2 and probably #3.

**Pull request merged**
